### ISSUE TITLE
Campanion issues

### ISSUE THREAD

**Issue by Acrivec** [Geometrically/Gravestones#29]
I've had some issues with the mod a couple of times, but usually destroying the gravestone once, then equipping backpack, then destroying it second time - fixed stuff.
But today I've lost everything inside my backpack. Items were duplicated - moving them over each other made them merge. Finally gravestone disappeared after I put everything I got in a chest, I've got back my exp but insides of backpack - gone.

Gravestones 1.9
Campanion 1.3.5
MC 1.16.5
```
[19:22:28] [Server thread/FATAL]: Error executing task on Server
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_2371.remove(class_2371.java:65) ~[intermediary-server.jar:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.SubList$1.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_281]
	at com.terraformersmc.campanion.compat.CampanionGravestonesCompat.setInventory(CampanionGravestonesCompat.java:31) ~[campanion-1.3.5.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.RetrieveGrave(GravestoneBlock.java:161) ~[gravestones-v1.9.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.method_9576(GravestoneBlock.java:68) ~[gravestones-v1.9.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:248) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:222) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:197) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[19:22:36] [Server thread/FATAL]: Error executing task on Server
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_2371.remove(class_2371.java:65) ~[intermediary-server.jar:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.SubList$1.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_281]
	at com.terraformersmc.campanion.compat.CampanionGravestonesCompat.setInventory(CampanionGravestonesCompat.java:31) ~[campanion-1.3.5.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.RetrieveGrave(GravestoneBlock.java:161) ~[gravestones-v1.9.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.method_9576(GravestoneBlock.java:68) ~[gravestones-v1.9.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:248) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:222) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:197) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[19:23:01] [Server thread/FATAL]: Error executing task on Server
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_2371.remove(class_2371.java:65) ~[intermediary-server.jar:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.SubList$1.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_281]
	at com.terraformersmc.campanion.compat.CampanionGravestonesCompat.setInventory(CampanionGravestonesCompat.java:31) ~[campanion-1.3.5.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.RetrieveGrave(GravestoneBlock.java:161) ~[gravestones-v1.9.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.method_9576(GravestoneBlock.java:68) ~[gravestones-v1.9.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:248) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:222) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:197) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[19:23:22] [Server thread/FATAL]: Error executing task on Server
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.remove(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.class_2371.remove(class_2371.java:65) ~[intermediary-server.jar:?]
	at java.util.AbstractList$Itr.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.SubList$1.remove(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collection.removeIf(Unknown Source) ~[?:1.8.0_281]
	at com.terraformersmc.campanion.compat.CampanionGravestonesCompat.setInventory(CampanionGravestonesCompat.java:31) ~[campanion-1.3.5.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.RetrieveGrave(GravestoneBlock.java:161) ~[gravestones-v1.9.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.method_9576(GravestoneBlock.java:68) ~[gravestones-v1.9.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:248) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:222) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:197) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1008) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:40) ~[intermediary-server.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:10) ~[intermediary-server.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

**Comment by Acrivec** [comment]
And now, crash.

```
[19:48:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 68
	at java.util.SubList.<init>(Unknown Source) ~[?:1.8.0_281]
	at java.util.AbstractList.subList(Unknown Source) ~[?:1.8.0_281]
	at net.guavy.gravestones.block.GravestoneBlock.RetrieveGrave(GravestoneBlock.java:161) ~[gravestones-v1.9.jar:?]
	at net.guavy.gravestones.block.GravestoneBlock.method_9576(GravestoneBlock.java:68) ~[gravestones-v1.9.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:248) ~[intermediary-server.jar:?]
	at net.minecraft.class_3225.method_14264(class_3225.java:103) ~[intermediary-server.jar:?]
	at net.minecraft.class_3222.method_5773(class_3222.java:379) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[intermediary-server.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
	... 5 more
[19:48:44] [Server thread/ERROR]: This crash report has been saved to: G:\Fabric server\mcss_win-x86-64_v11.13.0\servers\Misiowo\.\crash-reports\crash-2021-04-29_19.48.44-server.txt
[19:48:44] [Server thread/INFO]: [Dynmap] Unloaded 11 components.
[19:48:44] [Server thread/INFO]: [Dynmap] Stopping map renderer...
[19:48:45] [Server thread/INFO]: [Dynmap] Saved 6 pending tile renders in world 'Misiowo'
[19:48:45] [Server thread/INFO]: [Dynmap] Disabled
[19:48:45] [Server thread/INFO]: Stopping server
[19:48:45] [Server thread/INFO]: Saving players
[19:48:45] [Server thread/INFO]: Acrivec lost connection: Internal Exception: java.lang.StackOverflowError
[19:48:45] [Server thread/INFO]: Acrivec left the game
[19:48:45] [Server thread/ERROR]: Exception stopping the server
java.lang.IllegalStateException: Removing entity while ticking!
	at net.minecraft.class_3218.method_18774(class_3218.java:942) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18770(class_3218.java:958) ~[intermediary-server.jar:?]
	at net.minecraft.class_3324.method_14611(class_3324.java:385) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_10839(class_3244.java:1116) ~[intermediary-server.jar:?]
	at net.minecraft.class_2535.method_10768(class_2535.java:394) ~[intermediary-server.jar:?]
	at net.minecraft.class_1255.method_19537(class_1255.java:79) ~[intermediary-server.jar:?]
	at net.minecraft.class_3244.method_14367(class_3244.java:306) ~[intermediary-server.jar:?]
	at net.minecraft.class_3324.method_14597(class_3324.java:805) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:591) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:567) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:707) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]

```
